name: JIRENGU_CI

on: pull_request_target
jobs:
  homework-judgement:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      repository-projects: write
    steps:
      - name: Comment on PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
              ðŸŽ‰ æ„Ÿè°¢æ‚¨æäº¤Pull Requestï¼è¯·ç¨ç­‰ç‰‡åˆ»ï¼Œæˆ‘ä»¬å·²ç»å°†å…¶æäº¤åˆ°CIè¿›è¡Œæ£€æŸ¥ï¼Œä¸€æ—¦æœ‰ç»“æžœä¼šç«‹å³é€šçŸ¥æ‚¨ï¼
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and test with Maven
        run: mvn -B clean verify --file pom.xml

      - name: Comment PR if tests pass
        if: ${{ success() }}
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: 'All tests passed! ðŸŽ‰ Congratulation!ðŸŽ‰ðŸŽ‰ðŸŽ‰ We will revert your commit '
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          

      - name: Comment PR if tests fail
        if: ${{ failure() }}
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: 'Some tests failed. ðŸ˜ž Please check the [ci logs](${{ github.event.pull_request._links.html.href }}/checks) for more details.'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Merge PR if tests pass
        if: ${{ success() }}
        run: |
          # Merge PR
          response=$(curl -X PUT \
            -H "Authorization: token ${{ secrets.MY_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/merge)
          # Get the SHA of the merge commit
          sha=$(echo "$response" | jq -r '.sha')
          echo "merge_commit_sha=$sha" >> $GITHUB_ENV
          
      - name: Revert PR
        if: ${{ success() }}
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          # Checkout the main branch
          git checkout ${{ github.event.repository.default_branch }}

          # Revert the merge commit
          git revert -m 1 ${{ github.sha }}
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0 
        with:
          github_token: ${{ secrets.MY_TOKEN }}
          branch: ${{ github.ref }}     
